#include <iostream>
#include <thread>
#include <vector>
#include <cstring>
#include <atomic>
#include <chrono>
#include <unordered_set>
#include <mutex>
#include "fitsio.h"

// Test configuration mimicking AEGIS production workload
constexpr int NUM_THREADS = 16;      // Match AEGIS preprocessing workers (10-16)
constexpr int ITERATIONS = 2000;     // Sustained load over extended period
constexpr int FITS_SIZE = 2880;      // Standard FITS block size (36 * 80)

// Statistics tracking
std::atomic<int> success_count{0};
std::atomic<int> failure_count{0};
std::atomic<int> slot_collision_detected{0};

// For detecting slot collisions (multiple threads getting same handle)
std::mutex handle_tracking_mutex;
std::unordered_set<int> active_handles;

// Minimal valid FITS header for a 10x10 image (exactly fills 2880 bytes)
const char* create_fits_buffer(int thread_id, int iteration) {
    static thread_local char buffer[FITS_SIZE];
    std::memset(buffer, ' ', FITS_SIZE);
    
    // Standard FITS header (each line must be exactly 80 characters)
    const char* header_lines[] = {
        "SIMPLE  =                    T / file does conform to FITS standard             ",
        "BITPIX  =                  -32 / number of bits per data pixel                  ",
        "NAXIS   =                    2 / number of data axes                            ",
        "NAXIS1  =                   10 / length of data axis 1                          ",
        "NAXIS2  =                   10 / length of data axis 2                          ",
        "EXTEND  =                    T / FITS dataset may contain extensions            ",
        "COMMENT Generated by thread                                                     ",
        "END                                                                             "
    };
    
    int offset = 0;
    for (const char* line : header_lines) {
        std::memcpy(buffer + offset, line, 80);
        offset += 80;
    }
    
    // Fill rest with zeros (data section)
    std::memset(buffer + offset, 0, FITS_SIZE - offset);
    
    return buffer;
}

bool check_slot_collision(int handle, int thread_id, const char* operation) {
    std::lock_guard<std::mutex> lock(handle_tracking_mutex);
    
    if (strcmp(operation, "open") == 0) {
        if (active_handles.count(handle) > 0) {
            std::cerr << "SLOT COLLISION DETECTED! Thread " << thread_id 
                     << " got handle " << handle 
                     << " which is already in use by another thread!" << std::endl;
            slot_collision_detected++;
            return true;
        }
        active_handles.insert(handle);
    } else if (strcmp(operation, "close") == 0) {
        active_handles.erase(handle);
    }
    
    return false;
}

void stress_fits_memory_continuous(int thread_id) {
    auto start_time = std::chrono::steady_clock::now();
    
    for (int i = 0; i < ITERATIONS; i++) {
        // Create FITS buffer (thread-local, so no sharing)
        const char* fits_data = create_fits_buffer(thread_id, i);
        void* buffer = malloc(FITS_SIZE);
        std::memcpy(buffer, fits_data, FITS_SIZE);
        
        size_t buffsize = FITS_SIZE;
        fitsfile* fptr = nullptr;
        int status = 0;
        
        // === CRITICAL SECTION: This is where memTable race occurs ===
        fits_open_memfile(&fptr, "mem://test.fits", READONLY, 
                         &buffer, &buffsize, 0, nullptr, &status);
        
        if (status != 0) {
            failure_count++;
            char err_msg[81];
            fits_get_errstatus(status, err_msg);
            std::cerr << "Thread " << thread_id 
                     << " failed to open FITS file (iteration " << i 
                     << "), status=" << status 
                     << " (" << err_msg << ")" << std::endl;
            free(buffer);
            continue;
        }
        
        // Extract the internal handle for collision detection
        // Note: This is fragile but demonstrates the problem
        int handle = (fptr != nullptr) ? fptr->Fptr->filehandle : -1;
        
        // Check if we got a handle that another thread is using
        if (handle >= 0) {
            check_slot_collision(handle, thread_id, "open");
        }
        
        success_count++;
        
        // Simulate minimal work (AEGIS does FITS reading here)
        // Intentionally very short to maximize race window
        int naxis = 0;
        fits_get_img_dim(fptr, &naxis, &status);
        
        // Close immediately to stress slot recycling
        if (handle >= 0) {
            check_slot_collision(handle, thread_id, "close");
        }
        
        fits_close_file(fptr, &status);
        if (status != 0) {
            std::cerr << "Thread " << thread_id 
                     << " failed to close FITS file (iteration " << i << ")" << std::endl;
        }
        
        free(buffer);
        
        // === NO DELAY - Immediate recycling like AEGIS pipeline ===
        // This maximizes the probability of concurrent mem_openmem() calls
    }
    
    auto end_time = std::chrono::steady_clock::now();
    auto duration = std::chrono::duration_cast<std::chrono::milliseconds>(end_time - start_time);
    
    std::cout << "Thread " << thread_id << " completed " << ITERATIONS 
              << " iterations in " << duration.count() << "ms" << std::endl;
}

int main() {
    std::cout << "========================================" << std::endl;
    std::cout << "Enhanced CFITSIO Race Condition Test" << std::endl;
    std::cout << "Mimicking AEGIS Production Workload" << std::endl;
    std::cout << "========================================" << std::endl;
    std::cout << std::endl;
    
    std::cout << "Configuration:" << std::endl;
    std::cout << "  Threads: " << NUM_THREADS << " (matches AEGIS preprocessing workers)" << std::endl;
    std::cout << "  Iterations per thread: " << ITERATIONS << std::endl;
    std::cout << "  Total operations: " << (NUM_THREADS * ITERATIONS) << std::endl;
    std::cout << "  FITS block size: " << FITS_SIZE << " bytes" << std::endl;
    std::cout << std::endl;
    
    std::cout << "Architecture pattern:" << std::endl;
    std::cout << "  - Continuous operation (no artificial delays)" << std::endl;
    std::cout << "  - Immediate slot recycling (close → open)" << std::endl;
    std::cout << "  - High concurrency (all threads in tight loop)" << std::endl;
    std::cout << "  - Mimics AEGIS pipeline: Queue → Worker → FITS decode → Next" << std::endl;
    std::cout << std::endl;
    
    std::cout << "Race conditions being tested:" << std::endl;
    std::cout << "  1. memTable slot allocation (drvrmem.c:204-207)" << std::endl;
    std::cout << "  2. Fitsio_Pthread_Status global writes" << std::endl;
    std::cout << "  3. Slot collision detection (active handle tracking)" << std::endl;
    std::cout << std::endl;
    
    std::cout << "Starting test..." << std::endl;
    std::cout << "========================================" << std::endl;
    std::cout << std::endl;
    
    auto test_start = std::chrono::steady_clock::now();
    
    std::vector<std::thread> threads;
    
    // Launch worker threads simultaneously (maximizes initial contention)
    for (int i = 0; i < NUM_THREADS; i++) {
        threads.emplace_back(stress_fits_memory_continuous, i);
    }
    
    // Wait for completion
    for (auto& t : threads) {
        t.join();
    }
    
    auto test_end = std::chrono::steady_clock::now();
    auto total_duration = std::chrono::duration_cast<std::chrono::seconds>(test_end - test_start);
    
    std::cout << std::endl;
    std::cout << "========================================" << std::endl;
    std::cout << "Test Results" << std::endl;
    std::cout << "========================================" << std::endl;
    std::cout << "Total runtime: " << total_duration.count() << " seconds" << std::endl;
    std::cout << "Successful operations: " << success_count << std::endl;
    std::cout << "Failed operations: " << failure_count << std::endl;
    std::cout << "Slot collisions detected: " << slot_collision_detected << std::endl;
    std::cout << std::endl;
    
    if (failure_count > 0 || slot_collision_detected > 0) {
        std::cout << "RESULT: Race conditions DETECTED!" << std::endl;
        std::cout << std::endl;
        std::cout << "Evidence:" << std::endl;
        if (failure_count > 0) {
            std::cout << "  - " << failure_count << " FITS operations failed (likely due to memTable corruption)" << std::endl;
        }
        if (slot_collision_detected > 0) {
            std::cout << "  - " << slot_collision_detected << " slot collisions (multiple threads got same handle!)" << std::endl;
        }
        std::cout << std::endl;
        std::cout << "Analysis:" << std::endl;
        std::cout << "  The memTable race in drvrmem.c is REAL and reproducible." << std::endl;
        std::cout << "  This is the same issue affecting AEGIS in production." << std::endl;
        std::cout << std::endl;
        return 1;
    }
    
    std::cout << "RESULT: No immediate failures detected, but races may still exist!" << std::endl;
    std::cout << std::endl;
    std::cout << "Important notes:" << std::endl;
    std::cout << "  1. Race conditions are probabilistic - absence of failure doesn't mean absence of bug" << std::endl;
    std::cout << "  2. ThreadSanitizer will detect races even if they don't cause immediate failures" << std::endl;
    std::cout << "  3. AEGIS runs for hours with this pattern → eventually hits the race" << std::endl;
    std::cout << std::endl;
    std::cout << "Next steps:" << std::endl;
    std::cout << "  1. Rebuild CFITSIO with ThreadSanitizer:" << std::endl;
    std::cout << "     cd cfitsio-4.5.0" << std::endl;
    std::cout << "     make clean" << std::endl;
    std::cout << "     CFLAGS=\"-fsanitize=thread -g -O1\" LDFLAGS=\"-fsanitize=thread\" make" << std::endl;
    std::cout << std::endl;
    std::cout << "  2. Rebuild this test with ThreadSanitizer:" << std::endl;
    std::cout << "     g++ -std=c++17 -fsanitize=thread -g -O1 \\" << std::endl;
    std::cout << "         -I/path/to/cfitsio enhanced_cfitsio_race_test.cpp \\" << std::endl;
    std::cout << "         -L/path/to/cfitsio -lcfitsio -o enhanced_test" << std::endl;
    std::cout << std::endl;
    std::cout << "  3. Run with ThreadSanitizer options:" << std::endl;
    std::cout << "     TSAN_OPTIONS=\"history_size=7 second_deadlock_stack=1\" ./enhanced_test" << std::endl;
    std::cout << std::endl;
    
    return 0;
}
